<?php

include_once("index.html");
include_once("About_us.html");
include_once("Contact_Us.html");
include_once("FAQS.html");
include_once("Gallery.html");
include_once("Order_Form.html");
include_once("Reviews.html");
include_once("Product1.html");
include_once("Product2.html");
include_once("Product3.html");
include_once("Product4.html");
include_once("Product5.html");
include_once("Product6.html");
include_once("Product7.html");
include_once("Product8.html");
include_once("Product9.html");
include_once("Product10.html");
include_once("Product11.html");
include_once("Product12.html");
include_once("Product13.html");
include_once("Product14.html");
include_once("Product15.html");
include_once("products-condiments.html");
include_once("products-nuts.html");
include_once("products-special-offers.html");
include_once("products-spice.html");
include_once("products-valuepacks.html");
?>